// Read-only access to Hermes daily reports (agent/hermes/reports/*.md).
// Falls back to a bundled DEMO report when the directory is absent/empty
// (e.g. deployed without the repo tree), so the Reports UI always renders.

import fs from "fs";
import path from "path";

const REPORTS_DIR =
  process.env.DASHBOARD_REPORTS_DIR ||
  path.resolve(process.cwd(), "..", "agent", "hermes", "reports");

const DEMO_DATE = "2026-05-27";
const DEMO_REPORT = `# Daily Trading Intelligence Report

**Date (UTC)**: ${DEMO_DATE}
**Mode**: analysis-only (read-only SQLite, no broker connection)

> _DEMO report — illustrative of Hermes output. Generate real ones with_
> _\`python3 -m agent.hermes.daily_report --date YYYY-MM-DD\`._

## Signal Summary
- Total signals: **1680**
- Bullish: 812 (48.3%)
- Bearish: 798 (47.5%)
- Neutral: 70 (4.2%)

## Confidence Analysis
Forward 60s directional accuracy by confidence band
_(excludes stale, neutral, and observations with missing baseline/future tick)_

| Band | N | Accuracy |
|---|---:|---:|
| High (60-100) | 1290 | 55.8% |
| Medium (30-59) | 240 | 51.2% |
| Low (0-29) | 60 | 49.1% |

## Problems Found
- None detected by Phase 1 rules.

## Recommendations
- Continue collecting; high-confidence band edge (~56%) is promising but
  below the sample size needed to reject noise. Re-evaluate after a full week.

---
_Generated by Hermes (analysis-only). Hermes does not place trades, does not
connect to brokers, and does not bypass risk management._
`;

export function listReports(): string[] {
  try {
    const files = fs
      .readdirSync(REPORTS_DIR)
      .filter((f) => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
      .map((f) => f.replace(/\.md$/, ""))
      .sort()
      .reverse();
    if (files.length) return files;
  } catch {
    /* fall through to demo */
  }
  return [DEMO_DATE];
}

export function getReport(date: string): string | null {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return null;
  try {
    const file = path.join(REPORTS_DIR, `${date}.md`);
    if (fs.existsSync(file)) return fs.readFileSync(file, "utf-8");
  } catch {
    /* fall through */
  }
  if (date === DEMO_DATE) return DEMO_REPORT;
  return null;
}
