#include "phase6_test.hpp"
#include "oms/recovery.hpp"
namespace {exec::Journal valid(){exec::Journal j;(void)j.emit(exec::JournalRecordType::order_state,1,7,9,0,0,2,3,0,10);(void)j.emit(exec::JournalRecordType::command,1,7,9,0,0,0,10,11,1);(void)j.emit(exec::JournalRecordType::order_state,2,7,9,0,0,3,4,0,10);(void)j.emit(exec::JournalRecordType::acknowledgement,2,7,9,0,0,2);(void)j.emit(exec::JournalRecordType::fill,3,7,9,0,77,12,4,1,0);(void)j.emit(exec::JournalRecordType::order_state,3,7,9,0,0,4,7,4,10);(void)j.emit(exec::JournalRecordType::position_update,3,7,0,0,77,0,4,12,3);(void)j.emit(exec::JournalRecordType::account_update,4,7,0,0,0,100,104,10,94);(void)j.emit(exec::JournalRecordType::pnl_update,4,7,0,0,0,3,4,1,0);return j;}}
int main(){Phase6Test t;auto j=valid();oms::RecoveryState a(portfolio::MarginMode::hedging),b(portfolio::MarginMode::hedging);t.check(oms::recover(j,a,true,risk::HaltReason::manual_kill),"recover");t.check(oms::recover(j,b,true,risk::HaltReason::manual_kill),"repeat");t.check(a.orders.size()==1&&a.orders.at(0).state==exec::OrderState::unknown,"nonterminal unknown");// Invariant 5: "UNKNOWN orders reserve full exposure"; Part 8.5: exposure is
// "released only on a terminal state". The order requested 10 and filled 4, so
// the reservation stays at the full 10 — expecting the 6 remainder would mean a
// partial fill silently released exposure.
t.check(a.orders.reserved_exposure()==10&&b.orders.reserved_exposure()==10,"unknown reservation");t.check(a.positions.size()==1&&a.positions.at(0).volume==4,"pms");t.check(a.portfolio.symbol(0).gross==4&&a.portfolio.symbol(0).realized==3,"portfolio");t.check(a.account.balance_minor==100&&a.account.equity_minor==104&&a.account.margin_used_minor==10,"account");t.check(a.counters.commands==1&&a.counters.acks==1&&a.counters.fills==1,"counters");t.check(a.kill&&a.halt==risk::HaltReason::manual_kill,"halt");
 exec::Journal malformed;exec::JournalRecord r{};r.ts_ns=1;r.type=99;(void)malformed.append(r);oms::RecoveryState untouched(portfolio::MarginMode::hedging);t.check(!oms::recover(malformed,untouched),"malformed");t.check(untouched.orders.size()==0,"transactional failure");exec::Journal missing;(void)missing.emit(exec::JournalRecordType::fill,1,1,2,0,3,1,1,0,1);t.check(!oms::recover(missing,untouched),"missing dependency");exec::Journal dup;auto x=valid().at(0);(void)dup.append(x);x.seq=0;(void)dup.append(x);t.check(!oms::recover(dup,untouched),"duplicate");return t.result();}
