#include <chrono>
#include <filesystem>
#include <iostream>
#include "control/instance_lock.hpp"
#include "oms/oms.hpp"
#include "oms/pms.hpp"
#include "oms/reconciler.hpp"
#include "portfolio/portfolio.hpp"
#include "risk/kill_switch.hpp"
#include "risk/limits_verifier.hpp"
namespace {int fails=0;void ck(bool x,const char*n){if(!x){std::cout<<n<<"=FAIL\n";++fails;}}}
int main(){
 risk::Limits lim{};ck(risk::self_test(lim),"limits_self_test");auto bad=lim;bad.max_gross_exposure=1;bad.max_net_exposure=2;ck(!risk::self_test(bad),"limits_inconsistent");
 auto hash=risk::sha256("abc");const std::array<std::uint8_t,32>known={0xba,0x78,0x16,0xbf,0x8f,0x01,0xcf,0xea,0x41,0x41,0x40,0xde,0x5d,0xae,0x22,0x23,0xb0,0x03,0x61,0xa3,0x96,0x17,0x7a,0x9c,0xb4,0x10,0xff,0x61,0xf2,0x00,0x15,0xad};ck(hash==known,"sha256_known");ck(risk::verify("abc",known,lim),"limits_hash");auto wrong=known;wrong[0]^=1;ck(!risk::verify("abc",wrong,lim),"limits_mismatch");
 risk::RiskEngine engine(lim);risk::Request q{};q.symbol_id=0;q.strategy_id=1;q.volume=1;q.risk_minor=1;q.free_margin=1000000;q.warm_mask=1;q.session_open=true;auto decision=engine.check(q);ck(decision.approved,"risk_approved");
 oms::Oms orders;exec::BrokerOrderRef ref{1,2};auto*o=orders.create(ref,0,10,decision.token);ck(o!=nullptr,"oms_create");ck(orders.create(ref,0,10,decision.token)==nullptr,"oms_duplicate");ck(orders.transition(ref,exec::OrderState::sent),"oms_sent");ck(orders.transition(ref,exec::OrderState::unknown),"oms_unknown");ck(orders.reserved_exposure()==10,"unknown_reserved");ck(orders.resolve_unknown(ref,exec::OrderState::cancelled),"unknown_resolved");ck(orders.reserved_exposure()==0,"terminal_released");ck(!orders.transition(ref,exec::OrderState::sent),"terminal_closed");
 oms::Pms pms;ck(pms.open(7,0,exec::Side::buy)!=nullptr,"pms_opening");ck(pms.transition(7,exec::PositionState::open),"pms_open");ck(pms.modify(7,1),"pms_modify");ck(!pms.modify(7,1),"modify_idempotent");ck(pms.transition(7,exec::PositionState::open),"modify_ack");ck(pms.transition(7,exec::PositionState::closing),"pms_closing");ck(pms.transition(7,exec::PositionState::closed),"pms_closed");
 portfolio::Portfolio hedged(portfolio::MarginMode::hedging);ck(hedged.upsert(1,0,exec::Side::buy,10),"hedge_buy");ck(hedged.upsert(2,0,exec::Side::sell,4),"hedge_sell");ck(hedged.symbol(0).net==6&&hedged.symbol(0).gross==14,"hedge_aggregate");portfolio::Portfolio net(portfolio::MarginMode::netting);ck(net.upsert(1,0,exec::Side::buy,10),"net_one");ck(!net.upsert(2,0,exec::Side::sell,1),"net_reject_second_ticket");
 ck(risk::projected_free_margin(1000,100,1000,200)==880,"margin_projection");ck(!risk::self_trade_ok(true,false,1,2,10,exec::Side::sell),"self_trade_block");
 oms::ReconcileView rv{};ck(oms::reconciled(rv),"reconcile_equal");rv.orphan=true;ck(!oms::reconciled(rv),"reconcile_orphan");
 auto temp=std::filesystem::temp_directory_path()/("mme_phase6_"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));std::filesystem::create_directories(temp);risk::KillSwitch ks(temp/"state/kill.json");ck(!ks.halted_on_startup(),"kill_clear");ck(ks.trip(risk::HaltReason::manual_kill,1,2),"kill_persist");ck(ks.halted_on_startup(),"kill_restart");control::InstanceLock a,b;ck(a.acquire(temp/"engine.pid","mme_phase6_test"),"lock_first");ck(!b.acquire(temp/"engine.pid","mme_phase6_test"),"lock_second");a.release();ck(b.acquire(temp/"engine.pid","mme_phase6_test"),"lock_reacquire");b.release();std::error_code ec;std::filesystem::remove_all(temp,ec);
 risk::HaltSignals s{};s.pnl=-lim.max_daily_loss;ck(engine.evaluate(s)==risk::HaltReason::daily_loss,"halt_daily");s={};s.peak_equity=10000;s.equity=7000;ck(engine.evaluate(s)==risk::HaltReason::drawdown,"halt_dd");s={};s.consecutive_losses=lim.max_consecutive_losses;ck(engine.evaluate(s)==risk::HaltReason::consecutive_losses,"halt_losses");s={};s.feed_age_ms=lim.max_staleness_ms;ck(engine.evaluate(s)==risk::HaltReason::feed_stale,"halt_stale");s={};s.gap=true;ck(engine.evaluate(s)==risk::HaltReason::sequence_gap,"halt_gap");s={};s.ring_percent=100;ck(engine.evaluate(s)==risk::HaltReason::backpressure,"halt_bp");s={};s.latency_breach=true;ck(engine.evaluate(s)==risk::HaltReason::latency,"halt_latency");s={};s.reject_rate_bp=lim.max_reject_rate_bp+1;ck(engine.evaluate(s)==risk::HaltReason::reject_rate,"halt_reject");s={};s.connected=false;ck(engine.evaluate(s)==risk::HaltReason::disconnected,"halt_disconnect");s={};s.reconciliation_break=true;ck(engine.evaluate(s)==risk::HaltReason::reconciliation,"halt_reconcile");s={};s.lock_held=false;ck(engine.evaluate(s)==risk::HaltReason::instance_lock,"halt_lock");s={};s.stale_epoch=true;ck(engine.evaluate(s)==risk::HaltReason::stale_epoch,"halt_epoch");s={};s.disk_free_bytes=0;ck(engine.evaluate(s)==risk::HaltReason::disk,"halt_disk");s={};s.manual_kill=true;ck(engine.evaluate(s)==risk::HaltReason::manual_kill,"halt_manual");s={};s.control_kill=true;ck(engine.evaluate(s)==risk::HaltReason::control_kill,"halt_control");
 std::cout<<"phase6_failures="<<fails<<"\n";return fails?1:0;}
