"use client";

import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Card, DemoBanner } from "@/components/ui";
import { EmptyPanel, PanelError, PanelLoading } from "@/components/states";
import type { ReportPayload, ReportsPayload } from "@/lib/api-types";
import { useLiveData } from "@/lib/useLiveData";
import { PanelAction, StatusBadge } from "@/components/layout";
import { useSharedLiveData } from "@/components/live-context";

export default function ReportsPage() {
  const reportsQuery = useLiveData<ReportsPayload>("/api/reports");
  const { overview: overviewQuery } = useSharedLiveData();
  const [selected, setSelected] = useState<string | null>(null);
  useEffect(() => {
    if (!selected && reportsQuery.data?.dates.length) setSelected(reportsQuery.data.dates[0]);
  }, [reportsQuery.data, selected]);
  const reportQuery = useLiveData<ReportPayload>(selected ? `/api/reports/${selected}` : null);
  const provenance = overviewQuery.data ? <DemoBanner source={overviewQuery.data.source} sourceReason={overviewQuery.data.sourceReason} /> : overviewQuery.error ? <PanelError message={overviewQuery.error.message} retry={() => void overviewQuery.refresh()} /> : <PanelLoading label="Loading data provenance…" />;

  return (
    <div className="space-y-4 sm:space-y-5">
      {provenance}
      <div className="border-b border-edge/60 pb-4"><p className="text-[9px] uppercase tracking-[0.2em] text-accent/70">Intelligence archive</p><h1 className="mt-1 text-lg font-semibold tracking-tight text-slate-100 sm:text-xl">Hermes Reports</h1></div>
      <p className="text-[11px] leading-5 text-slate-600">
        Daily intelligence reports generated by the read-only Hermes analyst.
        Hermes does not place trades or connect to a broker.
      </p>

      <div className="grid gap-3.5 lg:grid-cols-[220px_minmax(0,1fr)]">
        <Card title="Reports" action={<PanelAction>UTC</PanelAction>} className="lg:sticky lg:top-24 lg:self-start">
          {reportsQuery.loading && !reportsQuery.data ? <PanelLoading label="Loading report dates…" /> : reportsQuery.error ? <PanelError message={reportsQuery.error.message} retry={() => void reportsQuery.refresh()} /> : reportsQuery.data?.dates.length ? (
            <ul className="space-y-1">
              {reportsQuery.data.dates.map((date) => (
                <li key={date}>
                  <button onClick={() => setSelected(date)} aria-pressed={selected === date} aria-label={`Open Hermes report for ${date}`} className={`group flex w-full items-center border-l-2 px-3 py-2.5 text-left text-xs transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-inset focus-visible:outline-accent ${selected === date ? "border-accent bg-accent/[0.08] text-accent" : "border-transparent text-slate-500 hover:bg-panel2 hover:text-slate-200"}`}>
                    <span>{date}</span><span className="ml-auto text-[9px] text-slate-700 transition-colors group-hover:text-slate-500" aria-hidden="true">→</span>
                  </button>
                </li>
              ))}
            </ul>
          ) : <EmptyPanel reason="Hermes has not generated any reports yet" />}
        </Card>

        {/* min-w-0: without it the grid item is sized by the report table's
            min-content width and scrolls the whole page on mobile. */}
        <Card className="min-w-0" title="Report document" action={reportQuery.data ? <StatusBadge tone="healthy">Available</StatusBadge> : reportQuery.error ? <StatusBadge tone="warning">Warning</StatusBadge> : <StatusBadge tone="unavailable">Unavailable</StatusBadge>}>
          {reportQuery.loading ? <PanelLoading label="Loading report…" /> : reportQuery.error ? <PanelError message={reportQuery.error.message} retry={() => void reportQuery.refresh()} /> : reportQuery.data ? (
            <article className="prose-report max-w-none text-[13px] leading-6">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{reportQuery.data.markdown}</ReactMarkdown>
            </article>
          ) : <EmptyPanel reason="Select a report to read it" />}
        </Card>
      </div>
    </div>
  );
}
