"use client";

import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import { Card } from "@/components/ui";

export default function ReportsPage() {
  const [dates, setDates] = useState<string[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [markdown, setMarkdown] = useState<string>("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/reports")
      .then((r) => r.json())
      .then((d: { dates: string[] }) => {
        setDates(d.dates);
        if (d.dates.length) setSelected(d.dates[0]);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  useEffect(() => {
    if (!selected) return;
    fetch(`/api/reports/${selected}`)
      .then((r) => r.json())
      .then((d: { markdown?: string }) => setMarkdown(d.markdown || "_Report not found._"));
  }, [selected]);

  return (
    <div>
      <h1 className="text-lg font-semibold text-slate-100 mb-1">Hermes Reports</h1>
      <p className="text-sm text-slate-500 mb-5">
        Daily intelligence reports generated by the read-only Hermes analyst.
        Hermes does not place trades or connect to a broker.
      </p>

      <div className="grid md:grid-cols-[200px_1fr] gap-4">
        <Card title="Reports">
          {loading ? (
            <p className="text-sm text-slate-500">Loading…</p>
          ) : (
            <ul className="space-y-1">
              {dates.map((d) => (
                <li key={d}>
                  <button
                    onClick={() => setSelected(d)}
                    className={`w-full text-left px-2 py-1 rounded text-sm ${
                      selected === d
                        ? "bg-accent/15 text-accent"
                        : "text-slate-400 hover:text-slate-200 hover:bg-panel2"
                    }`}
                  >
                    {d}
                  </button>
                </li>
              ))}
            </ul>
          )}
        </Card>

        <Card>
          <article className="prose-report max-w-none">
            <ReactMarkdown>{markdown}</ReactMarkdown>
          </article>
        </Card>
      </div>
    </div>
  );
}
